title: Ben Napier
email: ben@napier.xyz
description: Researcher
theme: jekyll-theme-minimal
permalink: pretty
collections:
  projects:
    output: true
    permalink: /projects/:path/
  resources:
    output: true
    permalink: /resources/:path/
  pages:
    output: true
    permalink: /pages/:path/